### ISSUE TITLE
double-check final output of demon / linking

### ISSUE THREAD

**Issue by AngryMaciek** [AngryMaciek/demon-runner#10]
Should we link by `output.dat` or maybe some other file?
Or maybe we should create an artificial temp. file if and only if demon finished successfully, link rules by this file and then delete it? 
Or maybe incorporate a tempfile at the end of demon?

Ask Rob

**Comment by AngryMaciek** [comment]
@vesmanojlovic : maybe you'd know this as well? :)

**Comment by vesmanojlovic** [comment]
Was just about to post! All the output files contain _slightly_ different information from each other so it really depends on the user which one they'd consider the main. However, I think `output.dat` gives the best summary. Will double-check this later today and update if I'm wrong.
