### ISSUE TITLE
docs: README

### ISSUE THREAD

**Issue by AngryMaciek** [AngryMaciek/demon-runner#12]
Prepare a nice clean README with:

- [x] general info
- [x] shields
- [x] installation instruction
- [x] exec
- [x] instruction how to parse to output
- [x] conda
- [x] links to papers

**Comment by vesmanojlovic** [comment]
Here's a couple, will check with Rob for more:
https://www.nature.com/articles/s41559-021-01615-9
https://onlinelibrary.wiley.com/doi/full/10.1111/eva.13057
